import argparse
import ast
import hashlib
import importlib
import subprocess
import sys
from pathlib import Path
from typing import Dict, List

# Dev-time only: renders roboi-ai-service prompt TEXT into src/core/prompts.py.
# The load test never imports roboi-main; it only reads the generated file.

EVENT_FILE = "roboi-ai-service/app/prompt/fallbacks/event_validation_prompt.py"
OFFICE_FILE = "roboi-ai-service/app/prompt/fallbacks/office_audit_prompt.py"
POLICY_FILE = "roboi-ai-service/app/prompt/policies/unified_event_policy_config.py"
EXTRACTION_FILE = "roboi-ai-service/app/services/search_analyzer.py"
EXTRACTION_FUNC = "extract_attributes_from_image"

OUT = Path(__file__).resolve().parents[1] / "core" / "prompts.py"

# Per-event values are left as markers and filled in by the task handlers at request time
EVENT_USER_FIELDS = [
    "company_id", "site_id", "cam_id", "cam_name", "site_name", "zone", "event_timestamp",
    "people_count", "vehicle_count", "animal_count", "triggers", "media_count", "detections", "recognitions",
]
OFFICE_USER_FIELDS = [
    "company_id", "device_id", "site_id", "cam_id", "cam_name", "zone_type", "timestamp",
    "detection_count", "people_count", "triggers", "detections", "recognitions", "media_count",
]


def marker(name: str) -> str:
    return f"⟪{name}⟫"


def git(repo: Path, *args: str) -> str:
    return subprocess.run(["git", "-C", str(repo), *args], capture_output=True, text=True, check=True).stdout.strip()


def extraction_prompt(source: Path) -> str:
    """Pull the inline `prompt = \"\"\"...\"\"\"` out of extract_attributes_from_image without importing it"""
    tree = ast.parse(source.read_text())
    for node in ast.walk(tree):
        if isinstance(node, ast.AsyncFunctionDef) and node.name == EXTRACTION_FUNC:
            for stmt in ast.walk(node):
                if (isinstance(stmt, ast.Assign) and isinstance(stmt.value, ast.Constant)
                        and any(isinstance(t, ast.Name) and t.id == "prompt" for t in stmt.targets)):
                    return stmt.value.value
    raise RuntimeError(f"prompt not found in {EXTRACTION_FUNC}")


def render(repo: Path) -> Dict:
    service_dir = repo / "roboi-ai-service"
    sys.path.insert(0, str(service_dir))
    event = importlib.import_module("app.prompt.fallbacks.event_validation_prompt")
    office = importlib.import_module("app.prompt.fallbacks.office_audit_prompt")
    policy = importlib.import_module("app.prompt.policies.unified_event_policy_config")

    bundle = policy.get_event_policy_bundle(company_id=None, site_id=None)
    domain, policy_context = bundle["selected_domain"], bundle["policy_context"]

    def kpi_line(trigger: str) -> str:
        rendered = event._render_kpi_prompt([trigger], policy_context, domain)
        header, _, line = rendered.partition("\n")
        assert header == "KPI PROMPTS", rendered
        return line

    office_user = office.USER_INSTRUCTIONS_TEMPLATE.format(
        **{f: marker(f) for f in OFFICE_USER_FIELDS}, **office.get_office_policy(None),
    )

    return {
        "EVENT_DOMAIN": domain,
        "EVENT_SYSTEM_HEADER": event.UNIVERSAL_SYSTEM_PROMPT.format(
            policy_reference=event._build_policy_reference(domain, policy_context)
        ).strip(),
        "EVENT_KPI_HEADER": "KPI PROMPTS",
        "EVENT_KPI_NO_TRIGGERS": event._render_kpi_prompt([], policy_context, domain),
        "EVENT_KPI_UNKNOWN": kpi_line(marker("trigger")),
        "EVENT_KPI_LINES": {t: kpi_line(t) for t in event.KPI_PROMPTS},
        "EVENT_OUTPUT_FORMAT": event.OUTPUT_RESPONSE_PROMPT.strip(),
        "EVENT_USER_TEMPLATE": event.UNIVERSAL_USER_PROMPT_TEMPLATE.format(
            **{f: marker(f) for f in EVENT_USER_FIELDS}
        ),
        "OFFICE_SYSTEM": office.build_system_prompt(None),
        "OFFICE_USER_TEMPLATE": office_user,
        "OFFICE_KPIS": list(office.ALL_KPIS),
        "EXTRACTION_PROMPT": extraction_prompt(repo / EXTRACTION_FILE),
    }


def py_str(s: str) -> str:
    body = s.replace("\\", "\\\\").replace('"""', '\\"""')
    return f'"""{body}"""'


def py_value(v, indent: int = 0) -> str:
    pad = " " * (indent + 4)
    if isinstance(v, str):
        return py_str(v)
    if isinstance(v, list):
        return "[\n" + "".join(f"{pad}{py_str(x)},\n" for x in v) + " " * indent + "]"
    if isinstance(v, dict):
        return "{\n" + "".join(f"{pad}{py_str(k)}: {py_value(x, indent + 4)},\n" for k, x in v.items()) + " " * indent + "}"
    raise TypeError(type(v))


def write(values: Dict, provenance: List[str], commit: str) -> str:
    digest = hashlib.sha256(repr(sorted(values.items())).encode()).hexdigest()[:8]
    version = f"{commit[:8]}-{digest}"
    lines = [
        "# GENERATED by `python -m src.services.prompt_snapshot` — do not edit by hand.",
        f"# Source: roboi-main @ {commit}",
        *[f"#   {p}" for p in provenance],
        "# Markers ⟪name⟫ are filled per request by the task handlers.",
        "",
        f'SOURCE_COMMIT = "{commit}"',
        f'PROMPT_VERSION = "{version}"',
        "",
    ]
    for name, value in values.items():
        lines += [f"{name} = {py_value(value)}", ""]
    OUT.write_text("\n".join(lines))
    return version


def main() -> int:
    parser = argparse.ArgumentParser(description="Snapshot roboi-ai-service prompt text into src/core/prompts.py")
    parser.add_argument("--source", type=Path, default=Path.home() / "roboi-main", help="roboi-main checkout")
    parser.add_argument("--allow-dirty", action="store_true", help="snapshot even if prompt files have local edits")
    args = parser.parse_args()

    repo = args.source.resolve()
    files = [EVENT_FILE, OFFICE_FILE, POLICY_FILE, EXTRACTION_FILE]
    dirty = git(repo, "status", "--porcelain", "--", *files, "roboi-ai-service/app/prompt")
    if dirty and not args.allow_dirty:
        print(f"❌ prompt files have uncommitted changes in {repo}:\n{dirty}", file=sys.stderr)
        return 1

    commit = git(repo, "rev-parse", "HEAD")
    provenance = [f"{f} (last changed {git(repo, 'log', '-1', '--format=%h', '--', f)})" for f in files]
    version = write(render(repo), provenance, commit)
    print(f"✅ Prompts pinned to roboi-main@{commit[:8]} → {OUT} (PROMPT_VERSION={version})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
